import { Request, Response, NextFunction } from 'express';
import * as reportService from '../services/report.service';

/**
 * POST /api/scans/:id/reports
 * Triggers PDF security report generation for a completed scan.
 */
export async function createScanReportController(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userId = req.user!.id;
    const scanId = req.params.id;

    const report = await reportService.generateReport(scanId, userId);

    res.status(201).json({
      success: true,
      data: { report },
      message: 'Security report generated successfully',
    });
  } catch (error) {
    next(error);
  }
}

/**
 * GET /api/reports/:id
 * Retrieves report metadata.
 */
export async function getReportController(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userId = req.user!.id;
    const reportId = req.params.id;

    const report = await reportService.getReportById(reportId, userId);

    res.status(200).json({
      success: true,
      data: { report },
    });
  } catch (error) {
    next(error);
  }
}

/**
 * GET /api/reports/:id/download
 * Securely streams the generated PDF report.
 */
export async function downloadReportController(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userId = req.user!.id;
    const reportId = req.params.id;

    const { stream, fileName, fileSize } = await reportService.getReportFileStream(
      reportId,
      userId
    );

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.setHeader('Content-Length', fileSize);
    res.setHeader('Content-Security-Policy', "default-src 'none'");
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');

    stream.pipe(res);
  } catch (error) {
    next(error);
  }
}

/**
 * GET /api/reports
 * Lists all reports generated by the authenticated user.
 */
export async function listUserReportsController(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userId = req.user!.id;
    const page = req.query.page ? parseInt(String(req.query.page), 10) : 1;
    const limit = req.query.limit ? parseInt(String(req.query.limit), 10) : 20;

    const result = await reportService.listUserReports(userId, { page, limit });

    res.status(200).json({
      success: true,
      data: result,
    });
  } catch (error) {
    next(error);
  }
}
